### PR TITLE
fix #42 Kotlin Doc rework after Dysprosium-RELEASE issues

### LINKED ISSUE #42: Link to Kotlin API Is Broken (404)
## Expected Behavior
On the [Documentation page](https://projectreactor.io/docs), the [Kotlin Doc](https://projectreactor.io/docs/core/release/kdoc-api/) should show the Kotlin API.

## Actual Behavior
The link shows a 404.

## Steps to Reproduce

1. Open the [Documentation page](https://projectreactor.io/docs).
2. Click on the [Kotlin Doc](https://projectreactor.io/docs/core/release/kdoc-api/) link under Reactor Core / Javadoc.

### PR DESCRIPTION
**Pull request by simonbasle**
- Removed the Kotlin Doc link from core and test sections
 - Replaced the Kotlin Doc link in kotlin-extensions section with
 javadoc link (see reactor/reactor-kotlin-extensions#3)
 - DocUtils takes these restrictions into account and we now redirect
 to a special 404 page to explain the situation, should one directly
 request a bad kdoc-api link

### CODE REVIEW

File: src/main/java/io/projectreactor/DocUtils.java [hunk 1]
```diff
@@ -122,6 +125,30 @@ else if (reqUri.contains("/kdoc-api/")) {
 		return url;
 	}
 
+	static boolean isKDocSpecialCases(String module, String version) {
+		if (("core".equals(module)
```
Comment (bsideup) [inline src/main/java/io/projectreactor/DocUtils.java]: same as https://github.com/reactor/projectreactor.io/pull/45/files#r329488488
